---
# tasks file for ansible-role-update-ubuntu
- name: "Gather facts"
  setup:    # equivalent to "gather_facts: yes"

- name: "Wait for any possibly running unattended upgrade to finish"
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: "Update apt package cache"
  apt:
    cache_valid_time: 1200

- name: "Get list of available updates"
  command: apt list --upgradable
  register: pkglist

- name: "Perform upgrade of all {{ pkglist.stdout_lines|length-1 }} upgradable packages to the latest version"
  apt:
    upgrade: dist
  when:
    - pkglist.rc == 0
    - pkglist.stdout_lines|length >= 1

- name: "Check if reboot is required"
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: "Reboot of {{ ansible_host }} is needed"
  reboot:
    reboot_timeout: 300
  when: reboot_required.stat.exists

- debug:
    msg: "{{ ansible_host }} is now back up and running!"